// BCC (body-centered-cubic) lattice math -- the second, interpenetrating
// lattice that is reciprocal/dual to the whole FCC lattice (src/core/
// lattice.js), not to be confused with dual.js's per-cell inscribed
// cube/octahedron. The FCC lattice's Voronoi cells are rhombic
// dodecahedra (RDs); this BCC lattice's Voronoi cells are truncated
// octahedra. Both are sublattices of the same integer coordinate space
// (Z^3): FCC is valid where x+y+z is EVEN (lattice.js's isValidCell),
// BCC is valid where x, y, z all share the same PARITY (all even or all
// odd) -- confirmed against lattice.js's own isValidCell/NEIGHBOR_OFFSETS
// in Phase 0 before writing this file.
//
// Pure math only -- no rendering, no Three.js import, per this task's
// Phase 1 scope. Phase 2 (render.js) reuses lattice.js's own
// cellToWorld(x, y, z, SCALE) transform directly rather than deriving a
// separate one here, since both lattices share the same coordinate space
// and the same world-space scale.

// True when (x, y, z) is a valid BCC lattice point: all three integer
// coordinates have the same parity (all even, or all odd). This is the
// standard integer embedding of the BCC lattice and is reciprocal to the
// x+y+z-even FCC embedding used throughout the rest of this codebase.
export function isBCC(x, y, z) {
  const px = ((x % 2) + 2) % 2;
  const py = ((y % 2) + 2) % 2;
  const pz = ((z % 2) + 2) % 2;
  return px === py && py === pz;
}

// 14 BCC neighbor offsets -- one per face of the truncated octahedron:
// 8 nearest neighbors (body-diagonal, all sign combinations of (1,1,1))
// correspond to its 8 hexagonal faces, and 6 second-nearest neighbors
// (axis-aligned, magnitude 2) correspond to its 6 square faces. Both sets
// preserve the "all same parity" BCC constraint: adding a body-diagonal
// offset flips all three coords' parity together (still all-equal), and
// adding an axis offset of magnitude 2 leaves every coord's parity
// unchanged.
export const BCC_NEIGHBOR_OFFSETS = [
  // 8 nearest (body-diagonal)
  [1, 1, 1], [1, 1, -1], [1, -1, 1], [1, -1, -1],
  [-1, 1, 1], [-1, 1, -1], [-1, -1, 1], [-1, -1, -1],
  // 6 second-nearest (axis)
  [2, 0, 0], [-2, 0, 0],
  [0, 2, 0], [0, -2, 0],
  [0, 0, 2], [0, 0, -2],
];

// The 24 vertices of the Voronoi cell of this BCC lattice -- a truncated
// octahedron -- scaled by `scale`. Every permutation of (0, 1, 2) with
// independent sign flips on the two nonzero entries (0 never gets a sign,
// since +0 === -0 would just duplicate the vertex). Generated by looping
// rather than hand-listed, per this task's own instruction, with a count
// self-check below.
export function truncatedOctahedronVertices(scale = 1) {
  const base = [0, 1, 2];
  const perms = [
    [0, 1, 2], [0, 2, 1],
    [1, 0, 2], [1, 2, 0],
    [2, 0, 1], [2, 1, 0],
  ];
  const verts = [];
  for (const [ia, ib, ic] of perms) {
    const a = base[ia];
    const b = base[ib];
    const c = base[ic];
    // a is always 0 by construction of these permutations' first slot
    // only when ia === 0 -- so don't assume position, instead sign-flip
    // whichever of a/b/c is nonzero independently, skipping flips on 0.
    const signsFor = (v) => (v === 0 ? [1] : [1, -1]);
    for (const sa of signsFor(a)) {
      for (const sb of signsFor(b)) {
        for (const sc of signsFor(c)) {
          verts.push([a * sa * scale, b * sb * scale, c * sc * scale]);
        }
      }
    }
  }
  // Dedupe: permutations where a coordinate is 0 in different slots can
  // otherwise coincide once sign-flipped (e.g. [0,1,2] and [0,2,1] both
  // produce a vertex with 0 in the first slot but from different source
  // permutations -- they are NOT the same point here since the nonzero
  // values differ in position, but guard with a Set keyed by rounded
  // coords anyway so any future edit that introduces a real duplicate
  // fails loudly via the count self-check below rather than silently.
  const seen = new Set();
  const unique = [];
  for (const v of verts) {
    const key = v.map((n) => n.toFixed(6)).join(',');
    if (!seen.has(key)) {
      seen.add(key);
      unique.push(v);
    }
  }
  return unique;
}

// Given an FCC cell coordinate (lattice.js convention: x+y+z even),
// returns its nearest BCC dual lattice points. Not wired into anything
// yet (Phase 3 stretch) -- exposed for future use by Duality Mode or
// growth-rule integration.
//
// Every FCC point sits at the centroid of a small tetrahedral cluster of
// BCC points; the nearest BCC points to any integer coordinate are found
// by rounding each axis to the nearest even or nearest odd value (whichever
// is closer) and checking both parity classes, since isBCC requires all
// three coords to share parity but a plain round() can land on mixed
// parity.
export function nearestBCCPoints(fccCoord) {
  const [x, y, z] = fccCoord;
  const results = [];
  for (const parity of [0, 1]) {
    // nearest integer of the given parity to each coordinate
    const snap = (v) => {
      const lo = Math.floor(v);
      const cand = [];
      for (let k = lo - 1; k <= lo + 2; k++) {
        if (((k % 2) + 2) % 2 === parity) cand.push(k);
      }
      return cand.reduce((best, c) => (Math.abs(c - v) < Math.abs(best - v) ? c : best));
    };
    const px = snap(x);
    const py = snap(y);
    const pz = snap(z);
    results.push([px, py, pz]);
  }
  // Dedupe (both parities can agree if fccCoord is already integer-aligned
  // to one parity class exactly).
  const seen = new Set();
  const unique = [];
  for (const p of results) {
    const key = p.join(',');
    if (!seen.has(key)) {
      seen.add(key);
      unique.push(p);
    }
  }
  return unique;
}

// Standalone sanity gate: run this file directly (node
// src/geometry-extensions/dual-lattice.js) to confirm the vertex-count
// math before Phase 2 touches any rendering.
if (typeof process !== 'undefined' && process.argv[1] && process.argv[1].endsWith('dual-lattice.js')) {
  const verts = truncatedOctahedronVertices(1);
  console.log(`truncatedOctahedronVertices(1) produced ${verts.length} vertices (expected 24).`);
  if (verts.length !== 24) {
    throw new Error(`Expected exactly 24 vertices, got ${verts.length}`);
  }
  console.log('isBCC checks:', {
    'origin (0,0,0) all-even -> true': isBCC(0, 0, 0),
    '(1,1,1) all-odd -> true': isBCC(1, 1, 1),
    '(1,1,0) mixed -> false': isBCC(1, 1, 0),
    '(2,0,0) all-even -> true': isBCC(2, 0, 0),
  });
  console.log(`BCC_NEIGHBOR_OFFSETS length: ${BCC_NEIGHBOR_OFFSETS.length} (expected 14).`);
  console.log('OK');
}
